# Generated by Django 3.1.7 on 2021-03-03 10:10

from django.db import migrations, models
import django.db.models.deletion
import recording.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('deadline_date', models.DateTimeField()),
                ('video', models.FileField(upload_to='uploads/%Y/%m/%d/', validators=[recording.validators.validate_video_file_extension])),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recording.question')),
            ],
        ),
    ]
