# Generated by Django 3.1.7 on 2021-03-07 18:32

import datetime
from django.db import migrations, models
import recording.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now)),
                ('video', models.FileField(upload_to='videos', validators=[recording.validators.validate_video_file_extension])),
            ],
        ),
    ]
