# Generated by Django 3.1.7 on 2021-03-06 19:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recording', '0002_auto_20210303_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='date published'),
        ),
    ]
