# Generated by Django 3.1.7 on 2021-03-06 23:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recording', '0003_auto_20210306_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
