# Generated by Django 3.1.7 on 2021-03-06 23:52

from django.db import migrations, models
import recording.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recording', '0004_auto_20210307_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='video',
            field=models.FileField(upload_to='videos', validators=[recording.validators.validate_video_file_extension]),
        ),
    ]
