# Generated by Django 3.1.7 on 2021-03-03 19:20

from django.db import migrations, models
import django.db.models.deletion
import homework.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_title', models.CharField(max_length=256)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('deadline_date', models.DateTimeField()),
                ('explanation', models.CharField(max_length=512)),
                ('document', models.FileField(upload_to='upload/%Y/%m/%d', validators=[homework.validators.validate_document_file_extension])),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_document', models.FileField(upload_to='upload/%Y/%m/%d', validators=[homework.validators.validate_document_file_extension])),
                ('score', models.DecimalField(decimal_places=2, max_digits=4, validators=[homework.validators.validate_score])),
                ('student_id', models.BigIntegerField(default=999988777)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homework.question')),
            ],
        ),
    ]
