# Generated by Django 3.1.7 on 2021-03-07 13:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import homework.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_title', models.CharField(max_length=256)),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='date published')),
                ('deadline_date', models.DateTimeField(default=datetime.datetime.now)),
                ('explanation', models.CharField(max_length=512)),
                ('document', models.FileField(upload_to='questions', validators=[homework.validators.validate_document_file_extension])),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_document', models.FileField(upload_to='answers', validators=[homework.validators.validate_document_file_extension])),
                ('score', models.IntegerField(null=True, validators=[homework.validators.validate_score])),
                ('upload_date', models.DateTimeField(default=datetime.datetime.now)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homework.question')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
