# Generated by Django 3.1.7 on 2021-03-04 23:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import homework.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homework', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='student_id',
        ),
        migrations.AddField(
            model_name='answer',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='answer',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True, validators=[homework.validators.validate_score]),
        ),
    ]
