# Generated by Django 3.1.7 on 2021-03-06 23:52

from django.db import migrations, models
import homework.validators


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0003_auto_20210305_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_document',
            field=models.FileField(upload_to='answers', validators=[homework.validators.validate_document_file_extension]),
        ),
        migrations.AlterField(
            model_name='question',
            name='document',
            field=models.FileField(upload_to='questions', validators=[homework.validators.validate_document_file_extension]),
        ),
    ]
